## === ENV PARAMS ===
java.version=25
vm.args=-Xmx512m -Xms256m -Dfile.encoding=UTF-8
#
## === MAIN PATHS ===
build.dir=build
dist.dir=dist
lib.dir=lib
tmp.dir=tmp
src.dir=src
main.java.dir=src/main/java
build.resources.dir=${build.dir}/main/resources
build.classes=${build.dir}/main/java
doc.dir=tmp/doc
WEB-INF.dir=build/main/webapp/WEB-INF
main.webapp.dir=src/main/webapp

main.class=main\java\Server.java
## === NAMES ===
project.name=WebLab3
#
## === COMP ARGS ===
compiler.args=-Xlint:all
tracked.classes=ant/conf/tracked-classes.txt
#
## === TEST PATHS ===
test.dir=src/test
test.classes=${build.dir}/test/java
test.resources=${build.dir}/test/resources
test.java.dir=src/test/java
test-report.dir=test-report
#
# === SERVER ===
scp.server=s465602@helios.cs.ifmo.ru:/home/studs/s465602
scp.port=2222
scp.password=mWEi=4227
#
# === SOUND ===
success-sound.wav=ant/conf/MEL1_sound.wav
fail-sound.wav=ant/conf/MEL2_sound.wav
#
## === NATIVE ENC ===
#native.encoding=UTF-8
#


# === ALT ===
replace.package.from=beans
replace.package.to=altbeans
replace.class.from=Utils
replace.class.to=AlternativeUtils
replace.var.from=validX
replace.var.to=allowedX


# === GIT REPO ===
git.repository=https://github.com/VlislV/OPI_LR3.git
git.clone.dir=${tmp.dir}/git-repo
git.revisions=HEAD~0 HEAD~1


# === SVN REPO ===
svn.local.repository=Documents/ITMO/OPI/LR_3/OPI_LR3_svn/trunk
svn.tracked_classes=ant/conf/tracked-classes.txt

# === ANT LIBS ===
ant-contrib.jar=ant/lib/ant-contrib-1.0b3.jar